/* 由 samples/storage.json 產生 src/samples.storage.ts。跑法：
     npm run gen:samples -w trace-sankey
   產物要 commit（使用端拿到的是編好的 dist，不會在他們那邊跑 codegen）。
   tools/test/samples.test.mjs 會斷言「重新產生的內容與磁碟上一致」，忘了跑會被抓到。

   為什麼是這個方向：samples/storage.json **原封不動**取自參考 repo
   （kube-state-graph-frontend public/demo/storage-graph.json，Apache-2.0），它只能當來源、
   不能是產生物。以前 samples.ts 裡另外手抄了一份同樣的資料（425 行），註解寫著
   「改一邊記得改另一邊」——這支就是把那份手抄拿掉。

   其餘 10 筆範例的來源仍是 samples.ts（N()／E() 簡寫，那是可讀的作者形式，
   轉成產生的 JSON 反而看不懂），samples/*.json 那 10 份由 samples.test.mjs 斷言內容一致。

   為什麼不直接 import JSON：套件是純 ESM + NodeNext，JSON import 要 import attributes，
   Vite dev（走 src/*.ts 條件）與 tsc 對它的支援不一致；產生一支 .ts 最單純，
   dist 裡也不必多一個 .json 檔。 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const PKG = join(dirname(fileURLToPath(import.meta.url)), '..');
const ROOT = join(PKG, '..', '..');
export const OUT = join(PKG, 'src/samples.storage.ts');
const SRC = join(ROOT, 'samples/storage.json');

/** 產生後的檔案內容（測試也用這支，不重複實作） */
export const generated = () => {
  const json = JSON.parse(readFileSync(SRC, 'utf8'));
  return '/* @generated by scripts/gen-samples.mjs（npm run gen:samples -w trace-sankey）——不要手改。\n'
    + '   來源：samples/storage.json，原封不動取自參考 repo\n'
    + '   https://github.com/akira-core/kube-state-graph-frontend public/demo/storage-graph.json\n'
    + '   @ 9e568c784b2ecb5ce87b201c73989fb21cb88c56（Apache-2.0）。\n'
    + '   那份 JSON 是唯一來源：以前 samples.ts 裡另外手抄了一份同樣的資料，註解寫著\n'
    + '   「改一邊記得改另一邊」——改成 codegen 之後不可能漂移。 */\n'
    + "import type { WireGraph } from './model/types.js';\n\n"
    + '/* 型別用 as unknown as：這是上游的 fixture，我們不改它的形狀，也不想為了讓一個\n'
    + '   產生的字面值通過結構比對而去動 WireGraph 的型別（真正的驗證是 validate()）。 */\n'
    + 'export const storageJson = '
    + JSON.stringify(json, null, 2).split('\n').join('\n')
    + ' as unknown as WireGraph;\n';
};

if (process.argv[1] && import.meta.url === new URL('file://' + process.argv[1]).href) {
  writeFileSync(OUT, generated());
  console.log('寫入 src/samples.storage.ts（來源 samples/storage.json）');
}
